---
sections:
- award_emoji:
    head: AWARD EMOJI METHODS
    doc_url: https://docs.gitlab.com/ce/api/award_emoji.html
- branches:
    head: BRANCH METHODS
    doc_url: https://doc.gitlab.com/ce/api/branches.html
- broadcast_messages:
    head: BROADCAST MESSAGE METHODS
    doc_url: https://docs.gitlab.com/ce/api/broadcast_messages.html
- project_level_variables:
    head: PROJECT LEVEL VARIABLE METHODS
    doc_url: https://docs.gitlab.com/ce/api/project_level_variables.html
- group_level_variables:
    head: GROUP LEVEL VARIABLE METHODS
    doc_url: https://docs.gitlab.com/ce/api/group_level_variables.html
- commits:
    doc_url: https://doc.gitlab.com/ce/api/commits.html
    head: COMMIT METHODS
- custom_attributes:
    doc_url: https://docs.gitlab.com/ce/api/custom_attributes.html
    head: CUSTOM ATTRIBUTE METHODS
- deployments:
    doc_url: https://docs.gitlab.com/ce/api/deployments.html
    head: DEPLOYMENT METHODS
- deploy_keys:
    head: DEPLOY KEY METHODS
    doc_url: https://docs.gitlab.com/ce/api/deploy_keys.html
- environments:
    head: ENVIRONMENT METHODS
    doc_url: https://docs.gitlab.com/ce/api/environments.html
- events:
    head: EVENT METHODS
    doc_url: https://docs.gitlab.com/ce/api/events.html
- features:
    head: FEATURE FLAG METHODS
    doc_url: https://docs.gitlab.com/ce/api/features.html
- gitignores_templates:
    head: GITIGNORES TEMPLATE METHODS
    doc_url: https://docs.gitlab.com/ce/api/templates/gitignores.html
- gitlab_ci_ymls_templates:
    head: GITLAB CI CONFIG TEMPLATE METHODS
    doc_url: https://docs.gitlab.com/ce/api/templates/gitlab_ci_ymls.html
- groups:
    head: GROUP METHODS
    doc_url: https://docs.gitlab.com/ce/api/groups.html
- group_access_requests:
    head: GROUP ACCESS REQUEST METHODS
    doc_url: https://docs.gitlab.com/ce/api/access_requests.html
- members:
    head: GROUP MEMBER METHODS
    doc_url: https://docs.gitlab.com/ce/api/members.html
- issues:
    head: ISSUE METHODS
    doc_url: https://docs.gitlab.com/ce/api/issues.html
- boards:
    head: ISSUE BOARD METHODS
    doc_url: https://docs.gitlab.com/ce/api/boards.html
- jobs:
    head: JOB METHODS
    doc_url: https://docs.gitlab.com/ce/api/jobs.html
- keys:
    head: KEY METHODS
    doc_url: https://docs.gitlab.com/ce/api/keys.html
- labels:
    head: LABEL METHODS
    doc_url: https://docs.gitlab.com/ce/api/labels.html
- merge_requests:
    head: MERGE REQUEST METHODS
    doc_url: https://docs.gitlab.com/ce/api/merge_requests.html
- milestones:
    head: PROJECT MILESTONE METHODS
    doc_url: https://docs.gitlab.com/ce/api/milestones.html
- group_milestones:
    head: GROUP MILESTONE METHODS
    doc_url: https://docs.gitlab.com/ce/api/group_milestones.html
- namespaces:
    head: NAMESPACE METHODS
    doc_url: https://docs.gitlab.com/ce/api/namespaces.html
- notes:
    head: NOTE METHODS
    doc_url: https://docs.gitlab.com/ce/api/notes.html
- notification_settings:
    head: NOTIFICATION SETTING METHODS
    doc_url: https://docs.gitlab.com/ce/api/notification_settings.html
- licenses_templates:
    head: OPEN SOURCE LICENSE TEMPLATE METHODS
    doc_url: https://docs.gitlab.com/ce/api/templates/licenses.html
- page_domains:
    head: PAGE DOMAIN METHODS
    doc_url: https://docs.gitlab.com/ce/api/pages_domains.html
- pipelines:
    head: PIPELINE METHODS
    doc_url: https://docs.gitlab.com/ce/api/pipelines.html
- pipeline_triggers:
    head: PIPELINE TRIGGER METHODS
    doc_url: https://docs.gitlab.com/ce/api/pipeline_triggers.html
- pipeline_schedules:
    head: PIPELINE SCHEDULE METHODS
    doc_url: https://docs.gitlab.com/ce/api/pipeline_schedules.html
- projects:
    head: PROJECT METHODS
    doc_url: https://docs.gitlab.com/ce/api/projects.html
- access_requests:
    head: PROJECT ACCESS REQUEST METHODS
    doc_url: https://docs.gitlab.com/ce/api/access_requests.html
- members:
    head: PROJECT MEMBER METHODS
    doc_url: https://docs.gitlab.com/ce/api/members.html
- project_snippets:
    head: PROJECT SNIPPET METHODS
    doc_url: https://docs.gitlab.com/ce/api/project_snippets.html
- protected_branches:
    head: PROTECTED BRANCH METHODS
    doc_url: https://docs.gitlab.com/ce/api/protected_branches.html
- repositories:
    head: REPOSITORY METHODS
    doc_url: https://docs.gitlab.com/ce/api/repositories.html
- repository_files:
    head: FILE METHODS
    doc_url: https://docs.gitlab.com/ce/api/repository_files.html
- runners:
    head: RUNNER METHODS
    doc_url: https://docs.gitlab.com/ce/api/runners.html
- services:
    head: SERVICE METHODS
    doc_url: https://docs.gitlab.com/ce/api/services.html
- settings:
    head: SETTINGS METHODS
    doc_url: https://docs.gitlab.com/ce/api/settings.html
- sidekiq_metrics:
    head: SIDEKIQ METRIC METHODS
    doc_url: https://docs.gitlab.com/ce/api/sidekiq_metrics.html
- system_hooks:
    head: SYSTEM HOOK METHODS
    doc_url: https://docs.gitlab.com/ce/api/system_hooks.html
- tags:
    head: TAG METHODS
    doc_url: https://docs.gitlab.com/ce/api/tags.html
- todos:
    head: TODO METHODS
    doc_url: https://docs.gitlab.com/ce/api/todos.html
- users:
    head: USER METHODS
    doc_url: https://docs.gitlab.com/ce/api/users.html
- lint:
    head: VALIDATE CI CONFIGURATION METHODS
    doc_url: https://docs.gitlab.com/ce/api/lint.html
- version:
    head: VERSION METHODS
    doc_url: https://docs.gitlab.com/ce/api/version.html
- wikis:
    head: WIKI METHODS
    doc_url: https://docs.gitlab.com/ce/api/wikis.html
